Repository YU-PLAYER/sportspie-was, pull requests merged in 2023-11, with the labels that each got.

#16 Feature banner
  src/main/java/com/example/sportspie/base/api/BannerApi.java
  src/main/java/com/example/sportspie/base/security/config/SecurityConfig.java
  src/main/java/com/example/sportspie/bounded_context/banner/controller/BannerController.java
  src/main/java/com/example/sportspie/bounded_context/banner/repository/BannerRepository.java
  src/main/java/com/example/sportspie/bounded_context/banner/service/BannerService.java
Labels: 배너

#24 알림 관련 기능 구현
  src/main/java/com/example/sportspie/base/api/NotificationApi.java
  src/main/java/com/example/sportspie/base/security/config/SecurityConfig.java
  src/main/java/com/example/sportspie/bounded_context/notification/controller/NotificationController.java
  src/main/java/com/example/sportspie/bounded_context/notification/dto/NotificationRequestDto.java
  src/main/java/com/example/sportspie/bounded_context/notification/entity/Notification.java
  src/main/java/com/example/sportspie/bounded_context/notification/repository/NotificationRepository.java
  src/main/java/com/example/sportspie/bounded_context/notification/service/NotificationService.java
Labels: 알림

#30 경기 관련 기능 구현
  src/main/java/com/example/sportspie/base/api/GameApi.java
  src/main/java/com/example/sportspie/base/security/config/SecurityConfig.java
  src/main/java/com/example/sportspie/bounded_context/game/controller/GameController.java
  src/main/java/com/example/sportspie/bounded_context/game/dto/GameListResponseDto.java
  src/main/java/com/example/sportspie/bounded_context/game/dto/GameRequestDto.java
  src/main/java/com/example/sportspie/bounded_context/game/dto/GameResultRequestDto.java
  src/main/java/com/example/sportspie/bounded_context/game/dto/GameUserRequestDto.java
  src/main/java/com/example/sportspie/bounded_context/game/entity/Game.java
  src/main/java/com/example/sportspie/bounded_context/game/repository/GameRepository.java
  src/main/java/com/example/sportspie/bounded_context/game/service/GameService.java
Labels: 경기

#31 경기장 관련 기능 구현 closes #28
  src/main/java/com/example/sportspie/base/api/StadiumApi.java
  src/main/java/com/example/sportspie/base/security/config/SecurityConfig.java
  src/main/java/com/example/sportspie/bounded_context/stadium/controller/StadiumController.java
  src/main/java/com/example/sportspie/bounded_context/stadium/dto/INearbyStadium.java
  src/main/java/com/example/sportspie/bounded_context/stadium/dto/NearbyStadiumRequestDto.java
  src/main/java/com/example/sportspie/bounded_context/stadium/repository/StadiumRepository.java
  src/main/java/com/example/sportspie/bounded_context/stadium/service/StadiumService.java
Labels: 경기장

#34 CORS 에러 해결 closes #33
  src/main/java/com/example/sportspie/base/security/config/SecurityConfig.java
Labels: bug

#35 cors-filter 구현 closes #33
  src/main/java/com/example/sportspie/base/api/AuthApi.java
  src/main/java/com/example/sportspie/base/security/config/SecurityConfig.java
  src/main/java/com/example/sportspie/base/security/filter/CorsFilter.java
Labels: bug

#37 사용자 본인 정보 조회 API 구현 closes #36
  src/main/java/com/example/sportspie/base/api/UserApi.java
  src/main/java/com/example/sportspie/bounded_context/auth/controller/UserController.java
  src/main/java/com/example/sportspie/bounded_context/auth/entity/User.java
  src/main/java/com/example/sportspie/bounded_context/auth/entity/UserPosition.java
  src/main/java/com/example/sportspie/bounded_context/auth/entity/UserRegion.java
  src/main/java/com/example/sportspie/bounded_context/auth/service/AuthService.java
Labels: 회원

#42 Feature game user
  src/main/java/com/example/sportspie/base/api/GameUserApi.java
  src/main/java/com/example/sportspie/bounded_context/gameUser/controller/GameUserController.java
  src/main/java/com/example/sportspie/bounded_context/gameUser/dto/GameUserRequestDto.java
  src/main/java/com/example/sportspie/bounded_context/gameUser/dto/JoinGameResponseDto.java
  src/main/java/com/example/sportspie/bounded_context/gameUser/dto/JoinUserResponseDto.java
  src/main/java/com/example/sportspie/bounded_context/gameUser/dto/UserRecordResponseDto.java
  src/main/java/com/example/sportspie/bounded_context/gameUser/entitiy/GameUser.java
  src/main/java/com/example/sportspie/bounded_context/gameUser/repository/GameUserRepository.java
  src/main/java/com/example/sportspie/bounded_context/gameUser/service/GameUserService.java
Labels: 경기유저

#43 Feature notification
  src/main/java/com/example/sportspie/base/api/NotificationApi.java
  src/main/java/com/example/sportspie/bounded_context/notification/controller/NotificationController.java
  src/main/java/com/example/sportspie/bounded_context/notification/repository/NotificationRepository.java
  src/main/java/com/example/sportspie/bounded_context/notification/service/NotificationService.java
Labels: 알림

#44 Feature exception
  src/main/java/com/example/sportspie/base/error/GlobalExceptionHandler.java
  src/main/java/com/example/sportspie/base/error/StateResponse.java
Labels: 예외

#45 경기 관련 기능 반환값 수정
  src/main/java/com/example/sportspie/base/api/GameApi.java
  src/main/java/com/example/sportspie/bounded_context/game/controller/GameController.java
  src/main/java/com/example/sportspie/bounded_context/game/dto/GameRequestDto.java
  src/main/java/com/example/sportspie/bounded_context/game/dto/GameUserRequestDto.java
  src/main/java/com/example/sportspie/bounded_context/game/entity/Game.java
  src/main/java/com/example/sportspie/bounded_context/game/service/GameService.java
Labels: 경기

#46 경기유저 관련 기능 반환값 및 오류 수정
  src/main/java/com/example/sportspie/base/api/GameUserApi.java
  src/main/java/com/example/sportspie/bounded_context/gameUser/controller/GameUserController.java
  src/main/java/com/example/sportspie/bounded_context/gameUser/repository/GameUserRepository.java
  src/main/java/com/example/sportspie/bounded_context/gameUser/service/GameUserService.java
Labels: 경기유저

#48 알림 관련 기능 수정
  src/main/java/com/example/sportspie/base/api/NotificationApi.java
  src/main/java/com/example/sportspie/bounded_context/notification/controller/NotificationController.java
  src/main/java/com/example/sportspie/bounded_context/notification/dto/NotificationRequestDto.java
  src/main/java/com/example/sportspie/bounded_context/notification/dto/NotificationResponseDto.java
  src/main/java/com/example/sportspie/bounded_context/notification/entity/Notification.java
  src/main/java/com/example/sportspie/bounded_context/notification/repository/NotificationRepository.java
  src/main/java/com/example/sportspie/bounded_context/notification/service/NotificationService.java
Labels: 알림

#49 경기 관련 기능 수정
  src/main/java/com/example/sportspie/base/api/GameApi.java
  src/main/java/com/example/sportspie/bounded_context/game/controller/GameController.java
  src/main/java/com/example/sportspie/bounded_context/game/dto/GameListResponseDto.java
  src/main/java/com/example/sportspie/bounded_context/game/dto/GameResponseDto.java
  src/main/java/com/example/sportspie/bounded_context/game/entity/Game.java
  src/main/java/com/example/sportspie/bounded_context/game/repository/GameRepository.java
  src/main/java/com/example/sportspie/bounded_context/game/service/GameService.java
Labels: 경기

#50 Game entity currentCapacity 필드 오류 수정
  src/main/java/com/example/sportspie/bounded_context/game/dto/GameRequestDto.java
  src/main/java/com/example/sportspie/bounded_context/game/entity/Game.java
Labels: 경기

#56 fix: 경기 인원 확정 API 헤더 토큰 사용으로 수정
  src/main/java/com/example/sportspie/base/api/GameApi.java
  src/main/java/com/example/sportspie/bounded_context/game/controller/GameController.java
  src/main/java/com/example/sportspie/bounded_context/game/service/GameService.java
Labels: 경기

#57 경기결과확정 API HttpServletRequest 사용
  src/main/java/com/example/sportspie/base/api/GameApi.java
  src/main/java/com/example/sportspie/bounded_context/game/controller/GameController.java
  src/main/java/com/example/sportspie/bounded_context/game/dto/GameResultRequestDto.java
  src/main/java/com/example/sportspie/bounded_context/game/service/GameService.java
Labels: 경기

#60 사용자 이미지 수정 API 구현 및 OAuth 로직 추가 구현
  build.gradle
  src/main/java/com/example/sportspie/base/api/UserApi.java
  src/main/java/com/example/sportspie/bounded_context/auth/config/GoogleConfig.java
  src/main/java/com/example/sportspie/bounded_context/auth/config/KakaoConfig.java
  src/main/java/com/example/sportspie/bounded_context/auth/config/S3Config.java
  src/main/java/com/example/sportspie/bounded_context/auth/controller/UserController.java
  src/main/java/com/example/sportspie/bounded_context/auth/dto/ImageUrlResponseDto.java
  src/main/java/com/example/sportspie/bounded_context/auth/dto/UserInfoDto.java
  src/main/java/com/example/sportspie/bounded_context/auth/service/GoogleService.java
  src/main/java/com/example/sportspie/bounded_context/auth/service/KakaoService.java
  src/main/java/com/example/sportspie/bounded_context/auth/service/S3Service.java
  src/main/java/com/example/sportspie/bounded_context/auth/service/UserService.java
Labels: 회원, 인증

#58 경기삭제 API HttpServletRequest 사용
  src/main/java/com/example/sportspie/base/api/GameApi.java
  src/main/java/com/example/sportspie/bounded_context/game/controller/GameController.java
  src/main/java/com/example/sportspie/bounded_context/game/service/GameService.java
Labels: 경기

#61 경기생성기능 API HttpServletRequest 사용
  src/main/java/com/example/sportspie/base/api/GameApi.java
  src/main/java/com/example/sportspie/bounded_context/game/controller/GameController.java
  src/main/java/com/example/sportspie/bounded_context/game/dto/GameUserRequestDto.java
  src/main/java/com/example/sportspie/bounded_context/game/service/GameService.java
Labels: 경기

#62 경기유저관련 API 수정
  src/main/java/com/example/sportspie/base/api/GameUserApi.java
  src/main/java/com/example/sportspie/bounded_context/gameUser/controller/GameUserController.java
  src/main/java/com/example/sportspie/bounded_context/gameUser/dto/GameUserRequestDto.java
  src/main/java/com/example/sportspie/bounded_context/gameUser/service/GameUserService.java
Labels: 경기유저

#63 delete API POST > DELETE 수정
  src/main/java/com/example/sportspie/base/api/GameApi.java
Labels: 경기

#64 Id 반환 추가
  src/main/java/com/example/sportspie/bounded_context/notification/dto/NotificationResponseDto.java
  src/main/java/com/example/sportspie/bounded_context/notification/entity/Notification.java
Labels: 알림

#65 매개변수 미일치 오류 수정
  src/main/java/com/example/sportspie/base/api/GameApi.java
  src/main/java/com/example/sportspie/bounded_context/game/controller/GameController.java
Labels: 경기

#67 경기참가 API 선호포지션 출력 수정
  src/main/java/com/example/sportspie/bounded_context/gameUser/dto/JoinUserResponseDto.java
  src/main/java/com/example/sportspie/bounded_context/gameUser/entitiy/GameUser.java
Labels: 경기
