Repository YU-PLAYER/sportspie-was, pull requests merged in 2023-12, with the labels that each got.

#68 Delete API cascade 추가 및 조건 수정
  src/main/java/com/example/sportspie/bounded_context/game/entity/Game.java
  src/main/java/com/example/sportspie/bounded_context/game/service/GameService.java
  src/main/java/com/example/sportspie/bounded_context/gameUser/repository/GameUserRepository.java
  src/main/java/com/example/sportspie/bounded_context/gameUser/service/GameUserService.java
Labels: 경기유저

#69 Detele API Transactional 추가
  src/main/java/com/example/sportspie/bounded_context/gameUser/service/GameUserService.java
Labels: 경기유저

#72 인원, 결과 확정 시간 조건 임시 삭제
  src/main/java/com/example/sportspie/bounded_context/game/service/GameService.java
Labels: 경기

#76 User API 테스트 코드 작성
  src/main/java/com/example/sportspie/bounded_context/auth/dto/UserInfoDto.java
  src/test/java/com/example/sportspie/bounded_context/auth/controller/UserControllerTest.java
Labels: test
