Repository YU-PLAYER/sportspie-was, pull requests merged in 2023-10, with the labels that each got.

#2 Swagger 연동
  build.gradle
  src/main/java/com/example/sportspie/config/SecurityConfig.java
  src/main/java/com/example/sportspie/config/SwaggerConfig.java
Labels: OAS

#7 Entity 일괄 생성 closes #3
  src/main/java/com/example/sportspie/bounded_context/auth/entity/User.java
  src/main/java/com/example/sportspie/bounded_context/auth/entity/UserPosition.java
  src/main/java/com/example/sportspie/bounded_context/auth/entity/UserRegion.java
  src/main/java/com/example/sportspie/bounded_context/auth/type/Position.java
  src/main/java/com/example/sportspie/bounded_context/game/entity/Game.java
  src/main/java/com/example/sportspie/bounded_context/game/type/GameResult.java
  src/main/java/com/example/sportspie/bounded_context/game/type/GameStatus.java
  src/main/java/com/example/sportspie/bounded_context/notification/entity/Notification.java
  src/main/java/com/example/sportspie/bounded_context/notification/type/NotificationType.java
  src/main/java/com/example/sportspie/bounded_context/stadium/entity/Stadium.java
  src/main/java/com/example/sportspie/bounded_context/stadium/type/Weather.java
Labels: 초기설정

#9 JWT 관련 기능 구현 인증 회원 closes #8
  build.gradle
  src/main/java/com/example/sportspie/SportspieApplication.java
  src/main/java/com/example/sportspie/base/jwt/config/JwtConfig.java
  src/main/java/com/example/sportspie/base/jwt/dto/JwtDto.java
  src/main/java/com/example/sportspie/base/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/example/sportspie/base/jwt/util/JwtProvider.java
  src/main/java/com/example/sportspie/base/security/config/SecurityConfig.java
Labels: 회원, 인증

#12 CI/CD 파이프라인 구현 close #11
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .gitignore
  Dockerfile
Labels: 초기설정, DevOps

#13 회원 인증 구현 인증 회원 closes #10
  build.gradle
  src/main/java/com/example/sportspie/base/api/AuthApi.java
  src/main/java/com/example/sportspie/bounded_context/auth/config/GoogleConfig.java
  src/main/java/com/example/sportspie/bounded_context/auth/config/KakaoConfig.java
  src/main/java/com/example/sportspie/bounded_context/auth/config/NaverConfig.java
  src/main/java/com/example/sportspie/bounded_context/auth/controller/AuthController.java
  src/main/java/com/example/sportspie/bounded_context/auth/dto/OAuthTokenRequestDto.java
  src/main/java/com/example/sportspie/bounded_context/auth/dto/OAuthUserInfoResponseDto.java
  src/main/java/com/example/sportspie/bounded_context/auth/entity/User.java
  src/main/java/com/example/sportspie/bounded_context/auth/repository/UserRepository.java
  src/main/java/com/example/sportspie/bounded_context/auth/service/AuthService.java
  src/main/java/com/example/sportspie/bounded_context/auth/service/GoogleService.java
  src/main/java/com/example/sportspie/bounded_context/auth/service/KakaoService.java
  src/main/java/com/example/sportspie/bounded_context/auth/service/NaverService.java
  src/main/java/com/example/sportspie/bounded_context/auth/service/OAuthBridge.java
  src/main/java/com/example/sportspie/bounded_context/auth/service/OAuthService.java
  src/main/java/com/example/sportspie/bounded_context/auth/service/UserService.java
  src/main/java/com/example/sportspie/bounded_context/auth/type/OAuthPlatform.java
Labels: 회원, 인증

#15 공지사항 관련 기능 구현 closes #14
  src/main/java/com/example/sportspie/base/api/NoticeApi.java
  src/main/java/com/example/sportspie/base/security/config/SecurityConfig.java
  src/main/java/com/example/sportspie/bounded_context/notice/controller/NoticeController.java
  src/main/java/com/example/sportspie/bounded_context/notice/repository/NoticeRepository.java
  src/main/java/com/example/sportspie/bounded_context/notice/service/NoticeService.java
Labels: 공지사항
